name: GoKart

on: [push, pull_request]

#on:
#  push:
#    branches: [ master, main ]
#  pull_request:
#    branches: [ master, main ]
#  schedule:
#    - cron: 0 0 * * *

jobs:
  gokart:
    name: GoKart scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run GoKart
        uses: kitabisa/gokart-action@v1.0.0
        with:
          globalsTainted: true

      - name: Upload GoKart results
        uses: github/codeql-action/upload-sarif@v1
